name: Python PEP8 Check

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Black
        uses: psf/black@stable
        with:
          options: "--check --diff --target-version=py310 --line-length=79"
          src: "./src/"
          version: "24.2.0"